name: test
on: [push]

jobs:
  terratest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: engineerd/setup-kind@v0.5.0
      - uses: fac/terratest-github-action@master