name: test
on: [push]

jobs:
  terratest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ~0.14.0
          terraform_wrapper: false
      - uses: helm/kind-action@v1.1.0
        with:
          cluster_name: kind
      - run: go test -v -timeout 30m
        working-directory: test